# -*- coding: utf-8 -*-
"""pythonarayüz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f5SYa9u_QOLHucUOIxMW9_o5nXKvs3rt
"""

!pip install gradio

import gradio as gr

# Hesaplama fonksiyonu
def hesapla(sayi1, sayi2, islem):
    try:
        sayi1 = float(sayi1)
        sayi2 = float(sayi2)

        if islem == "Toplama":
            return sayi1 + sayi2
        elif islem == "Çıkarma":
            return sayi1 - sayi2
        elif islem == "Çarpma":
            return sayi1 * sayi2
        elif islem == "Bölme":
            if sayi2 == 0:
                return "Hata: Sıfıra bölme yapılamaz."
            return sayi1 / sayi2
    except ValueError:
        return "Lütfen geçerli bir sayı giriniz."

# Gradio arayüzü
with gr.Blocks() as demo:
    with gr.Row():
        sayi1_input = gr.Textbox(label="Sayı 1")
        sayi2_input = gr.Textbox(label="Sayı 2")

    islem_secimi = gr.Dropdown(choices=["Toplama", "Çıkarma", "Çarpma", "Bölme"], label="İşlem Seçin")

    hesapla_btn = gr.Button("Hesapla")
    sonuc = gr.Textbox(label="Sonuç")

    hesapla_btn.click(hesapla, inputs=[sayi1_input, sayi2_input, islem_secimi], outputs=sonuc)

# Gradio arayüzünü başlat
demo.launch()